/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JObjArr */

#ifndef _Included_JObjArr
#define _Included_JObjArr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JObjArr
 * Method:    init2DArr
 * Signature: (II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_JObjArr_init2DArr
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
