/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JFieldMember */

#ifndef _Included_JFieldMember
#define _Included_JFieldMember
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JFieldMember
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JFieldMember_accessField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
