/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JCallBack */

#ifndef _Included_JCallBack
#define _Included_JCallBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JCallBack
 * Method:    callMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JCallBack_callMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
