/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello */

#ifndef _Included_hello
#define _Included_hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
