/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PromptString */

#ifndef _Included_PromptString
#define _Included_PromptString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PromptString
 * Method:    printStr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PromptString_printStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PromptString
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PromptString_getStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
