/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JArray */

#ifndef _Included_JArray
#define _Included_JArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JArray
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_JArray_sumArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
